[package]
name = "janus_server"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"
rust-version = "1.58"

[features]
tokio-console = ["console-subscriber"]

[dependencies]
anyhow = "1"
atty = "0.2"
base64 = "0.21.0"
bytes = "1.1.0"
chrono = "0.4"
console-subscriber = { version = "0.1.3", optional = true }
deadpool-postgres = "0.10.1"
derivative = "2"
hex = "0.4.3"
hpke = { version = "0.8.0", features = ["default", "std"] }
http = "0.2.6"
lazy_static = "1"
num_enum = "0.5.6"
postgres-types = { version = "0.2.2", features = ["derive"] }
prio = { git = "https://github.com/divviup/libprio-rs", rev = "229cd9c45924c7dae3ba754a6eb46b2a05ca8451" }  # TODO(brandon): use a numbered version, once a release is cut >0.7.0
rand = "0.8"
reqwest = { version = "0.11.4", default-features = false, features = ["rustls-tls", "json"] }
ring = "0.16.20"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
serde_yaml = "0.8.23"
structopt = "0.3.26"
testcontainers = "0.13.0"
thiserror = "1.0"
tokio = { version = "^1.9", features = ["full", "tracing"] }
tokio-postgres = { version = "0.7.5", features = ["with-chrono-0_4"] }
tracing = "0.1.32"
tracing-log = "0.1.2"
tracing-subscriber = { version = "0.3", features = ["std", "env-filter", "fmt", "json"] }
url = { version = "2.2.2", features = ["serde"] }
warp = { version = "^0.3", features = ["tls"] }

[dev-dependencies]
assert_matches = "1"
hyper = "0.14.17"
mockito = "0.31.0"
